### ISSUE TITLE
ExecuteJavaScript error

### ISSUE THREAD

**Issue by pony2323** [vuplex/oculus-webview-example#1]
hi ,  I need to get web page scroll offset, so I use javascript to get it. But it not work, can you help me? Thanks.

Code is here.

string getScrollHightFun = "var scrollHighdocumentElementFunc = function() { return document.documentElement.scrollTop; }\n";
            webView.WebView.ExecuteJavaScript(getScrollHightFun);
            string getScrollHigh = "scrollHighdocumentElementFunc();\n";
            int viewhight = 0;

            System.Action<string> action = HightCallbackAction;
            webView.WebView.ExecuteJavaScript(getScrollHigh, action);
            Task<string> hightTask = webView.WebView.ExecuteJavaScript(getScrollHigh);
            while (true)
            {
                if (hightTask.Exception != null)
                {
                    Debug.LogWarning(hightTask.Exception.InnerException.Message);
                    yield break;
                }

                if (hightTask.IsCompleted == true)
                {
                    break;
                }
                else
                {
                    yield return null;
                }
            }

            Debug.Log("viewhight string:" + hightTask.Result);
            viewhight = int.Parse(hightTask.Result);
            Debug.Log("viewhight: " + viewhight);

**Comment by BinaryNate** [comment]
Hi 👋 . Thank you for contacting me through [the support site](https://support.vuplex.com/contact) after creating this issue. The support site is the correct place for general 3D WebView support. Since I answered your question through the support site, I will close this issue. Here's the answer I sent you in case it is helpful to someone else:

> JavaScript executed via ExecuteJavaScript() runs in a closure, so it's unable to set global variables unless you set it directly on the window object. However, you can access scrollTop like this:

```
var scrollTop = await webViewPrefab.WebView.ExecuteJavaScript("document.scrollingElement.scrollTop");
```

> Note that for some web pages, scrolling occurs in an inner element instead of document.scrollingElement or document.documentElement, so the value returned may still be zero.
