### ISSUE TITLE
Setsurface does not work

### ISSUE THREAD

**Issue by syvn** [vuplex/oculus-webview-example#7]
Setsurface does not work

**Comment by binarynate** [comment]
Hi, @syvn 👋. Thank you for using 3D WebView! Sorry for my delayed response—I only use GitHub issues for issues specific to these example projects, so I don't check GitHub issues frequently. For general support, please use the [Vuplex contact page](https://vuplex.com/contact). First, can you please add logging to your application to confirm that SetSurface() is being called successfully as expected? For example, a NullReferenceException could be thrown if the application doesn't use WaitUntilInitialized() like shown in [this example](https://developer.vuplex.com/webview/AndroidWebView#SetSurface). If that doesn't resolve the issue, can you please send a message through the [Vuplex contact page](https://vuplex.com/contact) with the following info?

1. [Which 3D WebView for Android package](https://support.vuplex.com/articles/android-comparison) you're using.
2. Your script that calls SetSurface().
3. A description of the results you observe.
